ktor {
    deployment {
        port = ${?PORT}
        port = 8080
        sslPort = 8443
        host = 0.0.0.0
    }

    application {
        modules = [ com.empresa.fichaje.ApplicationKt.module ]
    }

    security {
        ssl {
            keyStore = keystore-mkcert.p12
            keyAlias = ktor
            keyStorePassword = changeit
            privateKeyPassword = changeit
        }
    }
}