package com.empresa.fichaje.domain.enums

enum class AccionPermitida {

    ENTRADA_TALLER,

    INICIO_DESCANSO_TALLER,
    FIN_DESCANSO_TALLER,
    SALIDA_TALLER,

    INICIO_VIAJE_OBRA,
    FIN_VIAJE_OBRA,
    ENTRADA_OBRA,
    SALIDA_OBRA,
    INICIO_DESCANSO_OBRA,
    FIN_DESCANSO_OBRA,

    INICIO_VIAJE_REPARACION,
    FIN_VIAJE_REPARACION,
    ENTRADA_REPARACION,
    SALIDA_REPARACION,
    INICIO_DESCANSO_REPARACION,
    FIN_DESCANSO_REPARACION,

    INICIO_VIAJE_TALLER,
    FIN_VIAJE_TALLER
}